[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "tests"
script = "scripts"
evm_version = 'paris'
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
gas_reports = ["TLAuctionHouse", "TLStacks721", "TLStacks1155"]
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arbitrum_sepolia = "${ARB_SEPOLIA_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
optimism_sepolia = "${OP_SEPOLIA_RPC_URL"
optimism = "${OP_RPC_URL"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum_sepolia = {  key = "${ARBISCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}" }
base_sepolia = {  key = "${BASESCAN_KEY}" }
base = { key = "${BASESCAN_KEY}" }
optimism_sepolia = {  key = "${OPSCAN_KEY}" }
optimism = { key = "${OPSCAN_KEY}" }